import os
import re
import json
import datetime as dt
from dataclasses import dataclass
from typing import Dict, Any, Optional, Tuple

import streamlit as st

# ============ Optional OpenAI support ============
# This app supports both:
# 1) OpenAI SDK v1.x (recommended)
# 2) Fallback "no-AI" mode (template-based) if API key is missing.
#
# For OpenAI SDK v1.x:
#   pip install openai>=1.0.0
#   then: from openai import OpenAI
try:
    from openai import OpenAI  # type: ignore
    OPENAI_AVAILABLE = True
except Exception:
    OPENAI_AVAILABLE = False


# ----------------------------
# Helpers
# ----------------------------
def slugify(text: str) -> str:
    text = text.lower().strip()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[\s_-]+", "-", text)
    text = re.sub(r"^-+|-+$", "", text)
    return text[:120] if len(text) > 120 else text


def sanitize_filename(name: str) -> str:
    name = re.sub(r"[^a-zA-Z0-9._-]+", "-", name).strip("-")
    return name or "output"


def wp_html_wrap(title: str, content_html: str) -> str:
    # WordPress accepts raw HTML content in the editor.
    # Wrap with minimal structure
    return f"""<article>
  <h1>{title}</h1>
  {content_html}
</article>
"""


def md_to_basic_html(md: str) -> str:
    """
    Minimal Markdown -> HTML converter for headings/bullets/paragraphs.
    Not perfect; good enough for WP-ready HTML.
    If you want full fidelity, use markdown library.
    """
    lines = md.splitlines()
    html_lines = []
    in_ul = False

    for line in lines:
        s = line.strip()
        if not s:
            if in_ul:
                html_lines.append("</ul>")
                in_ul = False
            html_lines.append("")
            continue

        # Headings
        if s.startswith("### "):
            if in_ul:
                html_lines.append("</ul>")
                in_ul = False
            html_lines.append(f"<h3>{s[4:].strip()}</h3>")
            continue
        if s.startswith("## "):
            if in_ul:
                html_lines.append("</ul>")
                in_ul = False
            html_lines.append(f"<h2>{s[3:].strip()}</h2>")
            continue
        if s.startswith("# "):
            if in_ul:
                html_lines.append("</ul>")
                in_ul = False
            html_lines.append(f"<h1>{s[2:].strip()}</h1>")
            continue

        # Bullets
        if s.startswith("- ") or s.startswith("* "):
            if not in_ul:
                html_lines.append("<ul>")
                in_ul = True
            html_lines.append(f"<li>{s[2:].strip()}</li>")
            continue

        # Paragraph
        if in_ul:
            html_lines.append("</ul>")
            in_ul = False
        # basic bold/italic
        p = s
        p = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", p)
        p = re.sub(r"\*(.+?)\*", r"<em>\1</em>", p)
        html_lines.append(f"<p>{p}</p>")

    if in_ul:
        html_lines.append("</ul>")

    return "\n".join([x for x in html_lines if x is not None])


def build_wxr_single_post(
    title: str,
    slug: str,
    content_html: str,
    excerpt: str,
    category: str,
    tags: str,
    status: str = "draft",
) -> str:
    """
    Very simplified WXR (WordPress eXtended RSS) for importing a single post.
    WP may still accept it; for production, you'd want a more complete WXR.
    """
    pub_date = dt.datetime.utcnow().strftime("%a, %d %b %Y %H:%M:%S +0000")
    post_date = dt.datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")

    tags_list = [t.strip() for t in tags.split(",") if t.strip()]
    tag_xml = "\n".join(
        [f'<category domain="post_tag" nicename="{slugify(t)}"><![CDATA[{t}]]></category>' for t in tags_list]
    )

    cat_xml = f'<category domain="category" nicename="{slugify(category)}"><![CDATA[{category}]]></category>' if category else ""

    # NOTE: content:encoded should be wrapped in CDATA
    return f"""<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0"
  xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
  xmlns:content="http://purl.org/rss/1.0/modules/content/"
  xmlns:wp="http://wordpress.org/export/1.2/">
<channel>
  <title>Streamlit Generated Export</title>
  <link>https://example.com</link>
  <description>Generated by Streamlit</description>
  <pubDate>{pub_date}</pubDate>
  <language>id-ID</language>

  <item>
    <title><![CDATA[{title}]]></title>
    <link>https://example.com/{slug}/</link>
    <pubDate>{pub_date}</pubDate>
    <dc:creator xmlns:dc="http://purl.org/dc/elements/1.1/"><![CDATA[admin]]></dc:creator>
    {cat_xml}
    {tag_xml}
    <guid isPermaLink="false">https://example.com/?p=1</guid>
    <description></description>
    <excerpt:encoded><![CDATA[{excerpt}]]></excerpt:encoded>
    <content:encoded><![CDATA[{content_html}]]></content:encoded>
    <wp:post_id>1</wp:post_id>
    <wp:post_date><![CDATA[{post_date}]]></wp:post_date>
    <wp:post_date_gmt><![CDATA[{post_date}]]></wp:post_date_gmt>
    <wp:post_name><![CDATA[{slug}]]></wp:post_name>
    <wp:status><![CDATA[{status}]]></wp:status>
    <wp:post_type><![CDATA[post]]></wp:post_type>
    <wp:is_sticky>0</wp:is_sticky>
  </item>
</channel>
</rss>
"""


@dataclass
class GeneratedContent:
    title: str
    meta_description: str
    outline_md: str
    article_md: str
    article_html: str
    wxr_xml: str
    slug: str
    raw: Dict[str, Any]


def template_generate(topic: str, keywords: str, tone: str, length: str) -> GeneratedContent:
    # Fallback generator without AI (basic template)
    kw = [k.strip() for k in keywords.split(",") if k.strip()]
    primary_kw = kw[0] if kw else topic

    title = f"{topic}: Panduan Lengkap ({dt.datetime.now().year})"
    meta = f"Pelajari {topic} secara lengkap: langkah, tips, dan contoh. Cocok untuk pemula. Kata kunci: {primary_kw}."
    outline = f"""## Pendahuluan
## Apa itu {topic}?
## Manfaat {topic}
## Langkah-langkah Praktis
- Persiapan
- Eksekusi
- Evaluasi
## Tips & Kesalahan Umum
## Contoh Penerapan
## FAQ
## Penutup
"""
    article = f"""# {title}

**Kata kunci utama:** {primary_kw}  
**Gaya bahasa:** {tone}  
**Panjang:** {length}

## Pendahuluan
{topic} adalah topik yang relevan untuk dibahas karena membantu pembaca memahami konsep dan penerapannya.

## Apa itu {topic}?
Jelaskan definisi {topic} dengan bahasa yang mudah dipahami. Sertakan konteks singkat.

## Manfaat {topic}
- Meningkatkan pemahaman dan efisiensi
- Mengurangi kesalahan umum
- Membantu membuat keputusan lebih baik

## Langkah-langkah Praktis
### Persiapan
Tuliskan apa saja yang perlu disiapkan.

### Eksekusi
Berikan langkah-langkah berurutan, gunakan poin agar mudah diikuti.

### Evaluasi
Cara mengecek hasil dan memperbaiki proses.

## Tips & Kesalahan Umum
Berikan tips ringkas dan daftar kesalahan yang sering terjadi.

## Contoh Penerapan
Berikan satu skenario contoh dan jelaskan hasilnya.

## FAQ
### Apa yang perlu dipelajari dulu?
Mulai dari dasar dan praktik sederhana.

### Berapa lama hasilnya terlihat?
Tergantung konteks, konsistensi, dan kompleksitas.

## Penutup
Rangkum poin penting dan beri ajakan untuk mencoba.
"""
    slug = slugify(title)
    html = wp_html_wrap(title, md_to_basic_html(article))
    wxr = build_wxr_single_post(
        title=title,
        slug=slug,
        content_html=html,
        excerpt=meta,
        category="Blog",
        tags=keywords,
        status="draft",
    )
    return GeneratedContent(
        title=title,
        meta_description=meta,
        outline_md=outline,
        article_md=article,
        article_html=html,
        wxr_xml=wxr,
        slug=slug,
        raw={"mode": "template"},
    )


def openai_generate(
    client: "OpenAI",
    topic: str,
    keywords: str,
    audience: str,
    tone: str,
    language: str,
    length: str,
    include_faq: bool,
    include_cta: bool,
) -> GeneratedContent:
    # You can switch to another model if you want
    model = "gpt-4o-mini"

    system = f"""You are an expert Indonesian SEO blog writer.
Output strictly as valid JSON with keys:
title, meta_description, outline_md, article_md.
Rules:
- Language: {language}
- Tone: {tone}
- Audience: {audience}
- Length: {length}
- Use keywords naturally: {keywords}
- Use Markdown headings with H2/H3.
- Avoid fluff; be practical and accurate.
- No plagiarism. No fabricated citations/claims.
"""
    user = {
        "topic": topic,
        "keywords": keywords,
        "audience": audience,
        "tone": tone,
        "language": language,
        "length": length,
        "include_faq": include_faq,
        "include_cta": include_cta,
        "requirements": [
            "Include a short intro and a clear conclusion.",
            "If include_faq is true, add an FAQ section with 3-5 Q&As.",
            "If include_cta is true, end with a gentle call-to-action.",
        ],
    }

    resp = client.chat.completions.create(
        model=model,
        response_format={"type": "json_object"},
        messages=[
            {"role": "system", "content": system},
            {"role": "user", "content": json.dumps(user, ensure_ascii=False)},
        ],
        temperature=0.7,
    )

    data = json.loads(resp.choices[0].message.content)

    title = data.get("title", topic).strip()
    meta = data.get("meta_description", "").strip()
    outline = data.get("outline_md", "").strip()
    article_md = data.get("article_md", "").strip()
    slug = slugify(title)

    article_html = wp_html_wrap(title, md_to_basic_html(article_md))
    wxr = build_wxr_single_post(
        title=title,
        slug=slug,
        content_html=article_html,
        excerpt=meta,
        category="Blog",
        tags=keywords,
        status="draft",
    )

    return GeneratedContent(
        title=title,
        meta_description=meta,
        outline_md=outline,
        article_md=article_md,
        article_html=article_html,
        wxr_xml=wxr,
        slug=slug,
        raw=data,
    )


# ----------------------------
# Streamlit UI
# ----------------------------
st.set_page_config(page_title="Auto Blog + WordPress Content Generator", page_icon="📝", layout="wide")
st.title("📝 Auto Generate Konten Blog & WordPress (Streamlit)")

st.write(
    "Bikin konten reusable (Markdown + HTML + WordPress XML). "
    "Deploy di Streamlit Community Cloud via GitHub."
)

with st.sidebar:
    st.header("⚙️ Pengaturan")
    mode = st.radio("Mode generator", ["AI (OpenAI)", "Template (tanpa AI)"], index=0)

    topic = st.text_input("Topik", value="Cara Membuat Landing Page untuk UMKM")
    keywords = st.text_input("Kata kunci (pisahkan koma)", value="landing page umkm, contoh landing page, tips landing page")
    audience = st.selectbox("Target audiens", ["Pemula", "UMKM", "Marketer", "Developer", "Umum"], index=1)
    tone = st.selectbox("Gaya bahasa", ["Santai", "Profesional", "Edukatif", "Persuasif"], index=2)
    language = st.selectbox("Bahasa", ["Indonesia", "English"], index=0)
    length = st.selectbox("Panjang", ["Pendek (~800 kata)", "Sedang (~1500 kata)", "Panjang (~2500 kata)"], index=1)

    include_faq = st.checkbox("Sertakan FAQ", value=True)
    include_cta = st.checkbox("Sertakan CTA (ajak action)", value=True)

    category = st.text_input("Kategori WP (untuk WXR)", value="Blog")
    status = st.selectbox("Status WP (untuk WXR)", ["draft", "publish"], index=0)

st.divider()

# Load API key (Streamlit secrets preferred)
api_key = None
if "OPENAI_API_KEY" in st.secrets:
    api_key = st.secrets["OPENAI_API_KEY"]
elif os.getenv("OPENAI_API_KEY"):
    api_key = os.getenv("OPENAI_API_KEY")

colA, colB = st.columns([1, 1])

with colA:
    st.subheader("🧩 Generate")
    generate_btn = st.button("Generate Konten", type="primary")

with colB:
    st.subheader("🔐 Status API")
    if mode == "AI (OpenAI)":
        if not OPENAI_AVAILABLE:
            st.error("Library OpenAI belum terpasang. Pastikan requirements.txt berisi openai>=1.0.0")
        elif not api_key:
            st.warning("OPENAI_API_KEY belum ada. App akan otomatis fallback ke Template mode.")
        else:
            st.success("OPENAI_API_KEY terdeteksi. Siap generate dengan AI.")
    else:
        st.info("Template mode aktif (tanpa AI).")

if "generated" not in st.session_state:
    st.session_state.generated = None

if generate_btn:
    with st.spinner("Sedang membuat konten..."):
        try:
            if mode == "AI (OpenAI)" and OPENAI_AVAILABLE and api_key:
                client = OpenAI(api_key=api_key)
                gen = openai_generate(
                    client=client,
                    topic=topic,
                    keywords=keywords,
                    audience=audience,
                    tone=tone,
                    language=language,
                    length=length,
                    include_faq=include_faq,
                    include_cta=include_cta,
                )
            else:
                gen = template_generate(topic=topic, keywords=keywords, tone=tone, length=length)

            # overwrite WXR with chosen category/status
            gen = GeneratedContent(
                title=gen.title,
                meta_description=gen.meta_description,
                outline_md=gen.outline_md,
                article_md=gen.article_md,
                article_html=gen.article_html,
                wxr_xml=build_wxr_single_post(
                    title=gen.title,
                    slug=gen.slug,
                    content_html=gen.article_html,
                    excerpt=gen.meta_description,
                    category=category,
                    tags=keywords,
                    status=status,
                ),
                slug=gen.slug,
                raw=gen.raw,
            )

            st.session_state.generated = gen
            st.success("Selesai ✅")
        except Exception as e:
            st.error(f"Gagal generate: {e}")

gen: Optional[GeneratedContent] = st.session_state.generated

if gen:
    st.subheader("✅ Hasil")

    tabs = st.tabs(["Ringkasan", "Markdown", "HTML (WP Ready)", "WordPress XML (WXR)", "JSON (debug)"])

    with tabs[0]:
        st.markdown(f"### {gen.title}")
        st.write(f"**Slug:** `{gen.slug}`")
        st.write(f"**Meta description:** {gen.meta_description}")
        st.markdown("**Outline:**")
        st.markdown(gen.outline_md)

    with tabs[1]:
        st.code(gen.article_md, language="markdown")
        fname = sanitize_filename(gen.slug) + ".md"
        st.download_button("Download .md", data=gen.article_md.encode("utf-8"), file_name=fname, mime="text/markdown")

    with tabs[2]:
        st.code(gen.article_html, language="html")
        fname = sanitize_filename(gen.slug) + ".html"
        st.download_button("Download .html", data=gen.article_html.encode("utf-8"), file_name=fname, mime="text/html")

    with tabs[3]:
        st.code(gen.wxr_xml, language="xml")
        fname = sanitize_filename(gen.slug) + ".xml"
        st.download_button("Download WXR .xml", data=gen.wxr_xml.encode("utf-8"), file_name=fname, mime="application/xml")

    with tabs[4]:
        st.json(gen.raw)

else:
    st.info("Klik **Generate Konten** untuk membuat output.")
